version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bi_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gizlisifre123
      POSTGRES_DB: bi_veritabani
    ports:
      - "5880:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: